<a href="https://colab.research.google.com/github/PauloSanchez/Data_science_UL/blob/main/Muestreo_conysin_reemplazo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Con reemplazo

In [1]:
# NumPy es bueno para ayudar a generar números aleatorios
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston

In [2]:
data = load_boston()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
df.head()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [3]:
# En el siguiente código, generará una lista de números aleatorios del 0 al 14
# es CON reemplazo. Verás duplicados
# Lo más probable es que no obtengas exactamente los mismos números que yo, ya que es aleatorio
np.random.choice(a=15, size=15, replace=True)

array([ 4,  7,  8,  9,  3, 13, 12,  4, 14, 12, 11,  8,  6,  5,  8])

In [4]:
# _ es un nombre de variable "desechable" de uso general para
# indicar que el valor producido por rango se ignora deliberadamente
# Lo más probable es que no obtengas exactamente los mismos números que yo, ya que es aleatorio
for _ in range(1, 15):
    samples = np.random.choice(a=15, size=15, replace=True)
    print(samples, ',Num Samples: ' + str(len(samples)) + ',numberUnique: ' + str(len(set(samples))) )

[ 6  4 12 13  6  1  8 13 12  9  1  2  4 10  0] ,Num Samples: 15,numberUnique: 10
[ 4 10 14  8  1 14 13 10  2  0  9  2 14  1 14] ,Num Samples: 15,numberUnique: 9
[14  7 10 14  3 12  8 10  7 10  3 10  7  4  6] ,Num Samples: 15,numberUnique: 8
[12 13 13  3 13 13  0 14 10  8  1 11 13 12  7] ,Num Samples: 15,numberUnique: 10
[14 11  1 11  4  5  0  4  4  3 13  4  6  5  6] ,Num Samples: 15,numberUnique: 9
[ 3 12  3  6  6  6  7  1  5 10 12 14  5 10  6] ,Num Samples: 15,numberUnique: 8
[ 2  9 12  7  5 13  6  9 11 13  7  7  7 12  8] ,Num Samples: 15,numberUnique: 9
[10  0  4 10  4 11  9 12  7  0 11 12  8  3  8] ,Num Samples: 15,numberUnique: 9
[ 4  3 12 14 10  7 11  5  8  1  5  9  0  7  4] ,Num Samples: 15,numberUnique: 12
[13 10 14 14 12 11 14  6  1  8  4  7 14  4  9] ,Num Samples: 15,numberUnique: 11
[ 7 14 13  1 14 14  4  6  0  4  5  5  9 10 10] ,Num Samples: 15,numberUnique: 10
[12  7  3 13 11 12  1  3  9  3  6  0  8 10 11] ,Num Samples: 15,numberUnique: 11
[ 3  0 11 11  8  5  3  1  6  6 12 

In [5]:
# mostrar las primeras 5 filas
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [8]:
# Mostrar las filas de la muestra de arranque
# Observa que tenemos 3 filas que comienzan con 10
bootstrappedDF = df.iloc[samples, :]

In [9]:
bootstrappedDF

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
5   0.02985   0.0   2.18   0.0  0.458  6.430   58.7  6.0622  3.0  222.0   
11  0.11747  12.5   7.87   0.0  0.524  6.009   82.9  6.2267  5.0  311.0   
10  0.22489  12.5   7.87   0.0  0.524  6.377   94.3  6.3467  5.0  311.0   
14  0.63796   0.0   8.14   0.0  0.538  6.096   84.5  4.4619  4.0  307.0   
3   0.03237   0.0   2.18   0.0  0.458  6.998   45.8  6.0622  3.0  222.0   
8   0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
8   0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
2   0.02729   0.0   7.07   0.0  0.469  7.185   61.1  4.9671  2.0  242.0   
0   0.00632  18.0   2.31   0.0  0.538  6.575   65.2  4.0900  1.0  296.0   
10  0.22489  12.5   7.87   0.0  0.524  6.377   94.3  6.3467  5.0  311.0   
9   0.17004  12.5   7.87   0.0  0.524  6.004   85.9  6.5921  5.0  311.0   
7   0.14455  12.5   7.87   0.0  0.524  6.172   96.1  5.9505  5.0  311.0   
1   0.02731   0.0   7.07   0.0  0.469  6.421   78.9  4.9671  2.0  242.0   
12  0.09378  12.5   7.87   0.0  0.524  5.889   39.0  5.4509  5.0  311.0   
3   0.03237   0.0   2.18   0.0  0.458  6.998   45.8  6.0622  3.0  222.0   

    PTRATIO       B  LSTAT  target  
5      18.7  394.12   5.21    28.7  
11     15.2  396.90  13.27    18.9  
10     15.2  392.52  20.45    15.0  
14     21.0  380.02  10.26    18.2  
3      18.7  394.63   2.94    33.4  
8      15.2  386.63  29.93    16.5  
8      15.2  386.63  29.93    16.5  
2      17.8  392.83   4.03    34.7  
0      15.3  396.90   4.98    24.0  
10     15.2  392.52  20.45    15.0  
9      15.2  386.71  17.10    18.9  
7      15.2  396.90  19.15    27.1  
1      17.8  396.90   9.14    21.6  
12     15.2  390.50  15.71    21.7  
3      18.7  394.63   2.94    33.4

#Sin reemplazo

In [ ]:
# En el siguiente código, generará una lista de números aleatorios del 0 al 14
# es SIN reemplazo. No duplicarás
# Lo más probable es que no obtengas exactamente los mismos números que yo, ya que es aleatorio
np.random.choice(a=15, size=15, replace=False)

In [10]:
# _ es un nombre de variable "desechable" de uso general para
# indicar que el valor producido por rango se ignora deliberadamente
# Lo más probable es que no obtengas exactamente los mismos números que yo, ya que es aleatorio
for _ in range(1, 15):
    samples = np.random.choice(a=15, size=15, replace=False)
    print(samples, ',Num Samples: ' + str(len(samples)) + ',numberUnique: ' + str(len(set(samples))) )

[ 8 14 10  9  1  4  5  6  3  7 12  0 13 11  2] ,Num Samples: 15,numberUnique: 15
[14  5  6  0  1 10 11 12  9  8  4 13  3  2  7] ,Num Samples: 15,numberUnique: 15
[ 9 12  1  0  4 10  6  5  8 14  7  2 11  3 13] ,Num Samples: 15,numberUnique: 15
[ 9  6  4  0  2  7  1 10 14 11 13  5 12  3  8] ,Num Samples: 15,numberUnique: 15
[ 7  6  1  8  9 14  5  0  4 11  2 13  3 10 12] ,Num Samples: 15,numberUnique: 15
[12  7  9 14 10 11  2  6  1 13  0  8  5  4  3] ,Num Samples: 15,numberUnique: 15
[ 0  8 10 14  3 11 12  1  6 13  9  4  7  5  2] ,Num Samples: 15,numberUnique: 15
[ 1 10  3  2  9  7 13 11  5 14  8  4  0  6 12] ,Num Samples: 15,numberUnique: 15
[ 6  0 11 13  4  7 12  5  9  8  2 10 14  1  3] ,Num Samples: 15,numberUnique: 15
[ 0 13 11  6 14  3  7 10  4  2  8  9  1 12  5] ,Num Samples: 15,numberUnique: 15
[ 6  1  7  0  3 13 10  9  2  4 14 11  8  5 12] ,Num Samples: 15,numberUnique: 15
[ 8 14  4  1  2 11  3  7  9  5 13  6 10 12  0] ,Num Samples: 15,numberUnique: 15
[ 3  7  4  5  6 14  0  8 11 

In [11]:
# mostrar las primeras 5 filas
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [ ]:
# Muestre las filas de la muestra SIN reemplazo
# Observa que no hay filas duplicadas
withoutDF = df.iloc[samples, :]

In [ ]:
# Show the rows generated with sample WITHOUT replacement
withoutDF.iloc[samples, :]