<a href="https://colab.research.google.com/github/PauloSanchez/Data_science_UL/blob/main/Tarea_WineData_Regresion_logistica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [3]:
#Codigo para definir el nombre de las columnas del DF, ya que este no las trae por defecto.
col_names = ['Class label', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium', 'Total phenols',
'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins','Color intensity', 'Hue', 'OD280/OD315 of diluted wines','Proline']

In [4]:
filename = '/content/drive/MyDrive/Colab Notebooks/Archivos ejercicios/wine.data.csv'
df = pd.read_csv(filename,header = None,names = col_names)
df.head()

Class label  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0            1    14.23        1.71  2.43               15.6        127   
1            1    13.20        1.78  2.14               11.2        100   
2            1    13.16        2.36  2.67               18.6        101   
3            1    14.37        1.95  2.50               16.8        113   
4            1    13.24        2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050  
2             5.68  1.03                          3.17     1185  
3             7.80  0.86                          3.45     1480  
4             4.32  1.04                          2.93      735

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Class label                   178 non-null    int64  
 1   Alcohol                       178 non-null    float64
 2   Malic acid                    178 non-null    float64
 3   Ash                           178 non-null    float64
 4   Alcalinity of ash             178 non-null    float64
 5   Magnesium                     178 non-null    int64  
 6   Total phenols                 178 non-null    float64
 7   Flavanoids                    178 non-null    float64
 8   Nonflavanoid phenols          178 non-null    float64
 9   Proanthocyanins               178 non-null    float64
 10  Color intensity               178 non-null    float64
 11  Hue                           178 non-null    float64
 12  OD280/OD315 of diluted wines  178 non-null    float64
 13  Proli

No se observan datos nulos.

In [6]:
df=df.drop_duplicates()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Class label                   178 non-null    int64  
 1   Alcohol                       178 non-null    float64
 2   Malic acid                    178 non-null    float64
 3   Ash                           178 non-null    float64
 4   Alcalinity of ash             178 non-null    float64
 5   Magnesium                     178 non-null    int64  
 6   Total phenols                 178 non-null    float64
 7   Flavanoids                    178 non-null    float64
 8   Nonflavanoid phenols          178 non-null    float64
 9   Proanthocyanins               178 non-null    float64
 10  Color intensity               178 non-null    float64
 11  Hue                           178 non-null    float64
 12  OD280/OD315 of diluted wines  178 non-null    float64
 13  Proli

No existen valores duplicados.

#Clasificación multiclase

In [7]:
# Imprimir cuántas clases
print('Class labels', np.unique(df['Class label']))



Class labels [1 2 3]


In [8]:
# Las clases no están equilibradas
df['Class label'].value_counts(dropna = False)



2    71
1    59
3    48
Name: Class label, dtype: int64

In [9]:
# Organizar los datos en la matriz de características y el vector de destino
X = df.loc[:, df.columns[(df.columns != 'Class label')]]
y = df.loc[:, 'Class label'].values



In [10]:
# En encuestas estadísticas,
# cuando las subpoblaciones dentro de una población general varían,
# Podría ser ventajoso muestrear cada subpoblación (estrato) de forma independiente
# La estratificación es el proceso de dividir a los miembros de la población en subgrupos homogéneos antes
# del muestreo.
# help(train_test_split)



In [11]:
# Dividir en conjuntos de prueba y entrenamiento
# Proporcionar la matriz de etiquetas de clase y como argumento para estratificar asegura a ambos
# el conjunto de entrenamiento y los conjuntos de datos de prueba tienen las mismas proporciones de clase que el
# conjunto de datos original
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)



In [12]:
unique, counts = np.unique(y_train, return_counts=True)
dict(zip(unique, counts))


{1: 41, 2: 50, 3: 33}

In [13]:
# Estandarizar datos
scaler = StandardScaler()
# Ajustar solo al conjunto de entrenamiento
scaler.fit(X_train)
# Aplicar  transform tanto al conjunto de entrenamiento como al conjunto de prueba
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

#Regresión logistica

In [14]:
log_reg = LogisticRegression(penalty='l1',
                        C=1.0,
                        solver='liblinear',
                        multi_class='ovr')
log_reg.fit(X_train, y_train)
print('Training accuracy:', log_reg.score(X_train, y_train))
print('Test accuracy:', log_reg.score(X_test, y_test))



Training accuracy: 1.0
Test accuracy: 1.0


In [15]:
log_reg.intercept_



array([-1.26356519, -1.21599762, -2.37140961])

In [16]:
log_reg.coef_



array([[ 1.24594022,  0.18060801,  0.74471497, -1.16246696,  0.        ,
         0.        ,  1.16558668,  0.        ,  0.        ,  0.        ,
         0.        ,  0.55188229,  2.50975856],
       [-1.53737277, -0.38736976, -0.99520916,  0.36497162, -0.05959051,
         0.        ,  0.66821465,  0.        ,  0.        , -1.93439539,
         1.23372722,  0.        , -2.23150056],
       [ 0.13533735,  0.16934284,  0.3577985 ,  0.        ,  0.        ,
         0.        , -2.43491748,  0.        ,  0.        ,  1.56244161,
        -0.81762507, -0.49656057,  0.        ]])

In [17]:
# La primera clase es la puntuación más alta, por lo que será la predicción 0 (la primera clase) para estos datos
log_reg.predict_proba(X_test[0:1])



array([[9.76618707e-01, 4.48103234e-04, 2.29331900e-02]])

In [18]:
# También podemos obtener la clase asociada con la probabilidad más alta
log_reg.predict(X_test[0:1])


array([1])

#KNN

In [19]:
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train, y_train)
knn.predict(X_train)


print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test, y_test)))


Accuracy of K-NN classifier on training set: 0.96
Accuracy of K-NN classifier on test set: 0.96


con 4 vecinos el modelo queda ajustado a un 96% de accuracy

In [20]:
pred = knn.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[18  0  0]
 [ 1 19  1]
 [ 0  0 15]]
              precision    recall  f1-score   support

           1       0.95      1.00      0.97        18
           2       1.00      0.90      0.95        21
           3       0.94      1.00      0.97        15

    accuracy                           0.96        54
   macro avg       0.96      0.97      0.96        54
weighted avg       0.97      0.96      0.96        54



#Bosques aleatoreos

In [27]:
from sklearn.ensemble import RandomForestClassifier

rndf_clf = RandomForestClassifier(n_estimators=20)
rndf_clf.fit(X_train, y_train)
rndf_clf.predict(X_test) #Guardo las predicciones
rndf_clf.score(X_test, y_test)


#Calculo la metrica entre y_val y y_val_pred, y aca va el reporte de clasificación
rndf_clf.score

<bound method ClassifierMixin.score of RandomForestClassifier(n_estimators=20)>